name: test and build

on:
    push:
        branches: master

jobs:
    test_backend:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - run: cd backend && pytest
